NagPy/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)

app_name = "Home"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", login, {"template_name": "nagpy/login.html"}, name="login"),
    path("logout/", logout, {"template_name": "nagpy/logout.html"}, name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.view_profile, name="view_profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/<int:pk>/", views.edit_event, name="edit_event"),
    path(
        "reset_password/",
        password_reset,
        {
            "template_name": "nagpy/reset_password.html",
            "post_reset_redirect": "Home:password_reset_done",
            "email_template_name": "nagpy/reset_password_email.html",
        },
        name="reset_password",
    ),
    path(
        "reset_password/done/",
        password_reset_done,
        {"template_name": "nagpy/reset_password_done.html"},
        name="password_reset_done",
    ),
    path(
        "reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/",
        password_reset_confirm,
        {
            "post_reset_redirect": "Home:password_reset_complete",
            "template_name": "nagpy/reset_password_confirm.html",
        },
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        password_reset_complete,
        {"template_name": "nagpy/reset_password_complete.html"},
        name="password_reset_complete",
    ),
    path("events/add/", views.event_add, name="add_event"),
    path("events/", views.events_view, name="events_view"),
    path("userprofile/edit/", views.userprofile_edit, name="userprofile_edit"),
]


NagPy/NagPy/urls.py
from django.contrib import admin
from django.urls import path, include
from NagPy import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home_redirect, name="login_redirect"),
    path("admin/", admin.site.urls),
    path("home/", include("Home.urls", namespace="Home")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NagPy/Home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Userprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=100, default="")
    city = models.CharField(max_length=100, default="")
    website = models.URLField(default="")
    phone = models.IntegerField(default=0)
    dp = models.ImageField(upload_to="dp_pics", blank=True)

    def __str__(self):
        return self.user.username


def create_porfile(sender, **kwargs):
    if kwargs["created"]:
        user_profile = Userprofile.objects.create(user=kwargs["instance"])


post_save.connect(create_porfile, sender=User)


class Event(models.Model):
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=100, default="")
    city = models.CharField(max_length=50, default="Nagpur")
    venue = models.CharField(max_length=200, default="")
    date = models.DateField()
    time = models.TimeField()
    contact = models.EmailField(default="")

    def __str__(self):
        return self.name

NagPy/Home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Event, Userprofile
from django.conf import settings


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    help_texts = {
        "password": "1> Your password can't be too similar to your other personal information 2> your password must contain at least 8 characters 3> your password can't be commonaly used password 4> your password can't be entirely numeric"
    }

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")
        exclude = ['username', 'password']
    def clean_password(self):
        return ""

class AddEventForm(forms.ModelForm):
    class Meta:
        model = Event
        help_texts = {
            "venue": "add detailed venue address",
            "time": "Time format is hr:min",
            "date": "mm/dd/yyyy",
        }
        fields = ("name", "city", "description", "venue", "date", "time", "contact")


class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = Userprofile
        exclude = ["user", "phone"]


class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("name", "city", "time", "date", "description", "venue", "contact")

NagPy/Home/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from Home.forms import (
    RegisterForm,
    EditProfileForm,
    AddEventForm,
    EditUserProfileForm,
    EditEventForm,
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from .models import Event, Userprofile

# Create your views here.


def home(request):
    return render(request, "nagpy/home.html")


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("Home:home"))
        else:
            return render(request, "nagpy/register.html", {"form": form})

    else:
        form = RegisterForm()
        args = {"form": form}
        return render(request, "nagpy/register.html", args)


def view_profile(request):
    args = {"user": request.user}
    return render(request, "nagpy/profile_view.html", args)


def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse("Home:view_profile"))
    else:
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request, "nagpy/edit_profile.html", args)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse("Home:view_profile"))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request, "nagpy/change_password.html", args)


def event_add(request):
    if request.method == "POST":
        form = AddEventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.manager = request.user
            event.save()
            return redirect(reverse("Home:events_view"))
        else:
            return render(request, "nagpy/event_add.html", {"form": form})
    else:
        form = AddEventForm()
        return render(request, "nagpy/event_add.html", {"form": form})


def events_view(request):
    event_list = Event.objects.all()
    args = {"events": event_list}
    return render(request, "nagpy/events_view.html", args)


def userprofile_edit(request):
    ins = get_object_or_404(Userprofile, pk=request.user.userprofile.pk)

    if request.method == "POST":
        form = EditUserProfileForm(request.POST, request.FILES, instance=ins)
        if form.is_valid():
            instance = form.save(commit=False)
            # userprofile.user = request.user
            instance.save()
            return redirect(reverse("Home:view_profile"))
        else:
            context = {
                "description": ins.description,
                "city": ins.city,
                "website": ins.website,
                "instance": ins,
                "form": form,
            }
            return render(request, "nagpy/userprofile_edit.html", context)
    else:
        form = EditUserProfileForm(instance=ins)
        context = {
            "description": ins.description,
            "city": ins.city,
            "website": ins.website,
            "instance": ins,
            "form": form,
        }
        return render(request, "nagpy/userprofile_edit.html", context)


def dashboard(request):
    event_list = Event.objects.filter(manager_id=request.user).all()
    args = {"events": event_list}
    return render(request, "nagpy/dashboard.html", args)


def edit_event(request, pk):
    usr = get_object_or_404(Event, pk=pk)

    if usr.manager == request.user:
        if request.POST:
            form = EditEventForm(request.POST, instance=usr)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                return redirect(reverse("Home:dashboard"))
            else:
                args = {"usr": usr, "pk": pk, "form": form}
                return render(request, "nagpy/edit_event.html", args)
        else:
            form = EditEventForm(instance=usr)
            args = {"usr": usr, "pk": pk, "form": form}
            return render(request, "nagpy/edit_event.html", args)
    else:
        return redirect(reverse("Home:dashboard"))


NagPy/Home/templates/base.1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script> {% block head %}
    <title>Nagpy</title>
    {% endblock %}
<script src="{% static 'js/script.js' %}"></script>
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <a class="navbar-brand" href="#">NagPY</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    {% if user.is_authenticated %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a href="{% url 'Home:logout' %}" class="dropdown-item">logout
                            </a>
                            <a href="{% url 'Home:view_profile' %}" class="dropdown-item">profile
                            </a>
                            <a href="{% url 'Home:edit_profile' %}" class="dropdown-item">edit Profile
                            </a>
                            <a href="{% url 'Home:change_password' %}" class="dropdown-item">change password
                            </a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Home:events_view' %}" class="nav-link">Events</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Home:add_event' %}" class="nav-link">Add New Event
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Home:dashboard' %}" class="nav-link">Dashboard
                        </a>
                    </li>





                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'Home:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Home:register' %}" class="nav-link">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'Home:login' %}" class="nav-link">Signin
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block body %}
        <h1>base</h1>
        {% endblock %}
    <footer class="footer-cont">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>
    </div>
</body>


</html>

NagPy/Home/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script> -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script> {% block head %}
    <title>Nagpy</title>
    {% endblock %}

</head>

<body>
   
    <div class="container-fluid">
         <div class="button_container" id="toggle">
             {% block bodytitle %}
             <div class="body-title" id="ttl">Base</div>
             {% endblock %}
             <div class="bar">
  <span class="top"></span>
  <span class="middle"></span>
  <span class="bottom"></span>
  </div>
</div>
        <div class="overlay" id="overlay">
        <nav class="overlay-menu">
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'Home:logout' %}">logout
                        </a></li>
                        <li>
                       <a href="{% url 'Home:view_profile' %}">profile</a>

                    </li>
                    <li>
                            <a href="{% url 'Home:edit_profile' %}">edit Profile
                                </a>
                    </li>
                    <li>
                            <a href="{% url 'Home:change_password' %}">change password
                                </a>
                    </li>
                    <li>
                        <a href="{% url 'Home:events_view' %}" >Events</a>
                    </li>
                    <li>
                        <a href="{% url 'Home:add_event' %}" >Add New Event
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'Home:dashboard' %}" >Dashboard
                        </a>
                    </li>





                    {% else %}
                    <li >
                        <a href="{% url 'Home:home' %}" >Home</a>
                    </li>
                    <li >
                        <a href="{% url 'Home:register' %}" >Signup</a>
                    </li>
                    <li >
                        <a href="{% url 'Home:login' %}">Signin
                        </a>
                    </li>
                    {% endif %}
                    <li id="social-link">

                        <a href="">
                            {% load static %}
                            <img src="{% static 'images/slack.svg' %}" alt="" height="50px" width="50px">
                        </a>
                        <a href="">
                                {% load static %}
                                <img src="{% static 'images/fb.svg' %}" alt="" height="50px" width="50px">
                            </a>
                            <a href="">
                                    {% load static %}
                                    <img src="{% static 'images/twitter.svg' %}" alt="" height="50px" width="50px">
                                </a>
                    </li>
                    <li>

                        <small class="text-muted" style="font-size:15px; color:white; text-transform:none">Copyright &copy; 2018 NagPy</small>
                    </li>
                </ul>
            </nav>
            <footer>
                hello
            </footer>
        </div>

        <div class="body-container">
        {% block body %}
        <h1>base</h1>
        {% endblock %}
        </div>

    </div>
</body>

</html>