NagPy/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)

app_name = "Home"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", login, {"template_name": "nagpy/login.html"}, name="login"),
    path("logout/", logout, {"template_name": "nagpy/logout.html"}, name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.view_profile, name="view_profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/<int:pk>/", views.edit_event, name="edit_event"),
    path(
        "reset_password/",
        password_reset,
        {
            "template_name": "nagpy/reset_password.html",
            "post_reset_redirect": "Home:password_reset_done",
            "email_template_name": "nagpy/reset_password_email.html",
        },
        name="reset_password",
    ),
    path(
        "reset_password/done/",
        password_reset_done,
        {"template_name": "nagpy/reset_password_done.html"},
        name="password_reset_done",
    ),
    path(
        "reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/",
        password_reset_confirm,
        {
            "post_reset_redirect": "Home:password_reset_complete",
            "template_name": "nagpy/reset_password_confirm.html",
        },
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        password_reset_complete,
        {"template_name": "nagpy/reset_password_complete.html"},
        name="password_reset_complete",
    ),
    path("events/add/", views.event_add, name="add_event"),
    path("events/", views.events_view, name="events_view"),
    path("userprofile/edit/", views.userprofile_edit, name="userprofile_edit"),
]


NagPy/NagPy/urls.py
from django.contrib import admin
from django.urls import path, include
from NagPy import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home_redirect, name="login_redirect"),
    path("admin/", admin.site.urls),
    path("home/", include("Home.urls", namespace="Home")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NagPy/Home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Userprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=100, default="")
    city = models.CharField(max_length=100, default="")
    website = models.URLField(default="")
    phone = models.IntegerField(default=0)
    dp = models.ImageField(upload_to="dp_pics", blank=True)

    def __str__(self):
        return self.user.username


def create_porfile(sender, **kwargs):
    if kwargs["created"]:
        user_profile = Userprofile.objects.create(user=kwargs["instance"])


post_save.connect(create_porfile, sender=User)


class Event(models.Model):
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=100, default="")
    city = models.CharField(max_length=50, default="Nagpur")
    venue = models.CharField(max_length=200, default="")
    date = models.DateField()
    time = models.TimeField()
    contact = models.EmailField(default="")

    def __str__(self):
        return self.name

NagPy/Home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Event, Userprofile
from django.conf import settings


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    help_texts = {
        "password": "1> Your password can't be too similar to your other personal information 2> your password must contain at least 8 characters 3> your password can't be commonaly used password 4> your password can't be entirely numeric"
    }

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")
        exclude = ['username', 'password']
    def clean_password(self):
        return ""

class AddEventForm(forms.ModelForm):
    class Meta:
        model = Event
        help_texts = {
            "venue": "add detailed venue address",
            "time": "Time format is hr:min",
            "date": "mm/dd/yyyy",
        }
        fields = ("name", "city", "description", "venue", "date", "time", "contact")


class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = Userprofile
        exclude = ["user", "phone"]


class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("name", "city", "time", "date", "description", "venue", "contact")

NagPy/Home/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from Home.forms import (
    RegisterForm,
    EditProfileForm,
    AddEventForm,
    EditUserProfileForm,
    EditEventForm,
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from .models import Event, Userprofile

# Create your views here.


def home(request):
    return render(request, "nagpy/home.html")


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("Home:home"))
        else:
            return render(request, "nagpy/register.html", {"form": form})

    else:
        form = RegisterForm()
        args = {"form": form}
        return render(request, "nagpy/register.html", args)


def view_profile(request):
    args = {"user": request.user}
    return render(request, "nagpy/profile_view.html", args)


def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse("Home:view_profile"))
    else:
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request, "nagpy/edit_profile.html", args)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse("Home:view_profile"))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request, "nagpy/change_password.html", args)


def event_add(request):
    if request.method == "POST":
        form = AddEventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.manager = request.user
            event.save()
            return redirect(reverse("Home:events_view"))
        else:
            return render(request, "nagpy/event_add.html", {"form": form})
    else:
        form = AddEventForm()
        return render(request, "nagpy/event_add.html", {"form": form})


def events_view(request):
    event_list = Event.objects.all()
    args = {"events": event_list}
    return render(request, "nagpy/events_view.html", args)


def userprofile_edit(request):
    ins = get_object_or_404(Userprofile, pk=request.user.userprofile.pk)

    if request.method == "POST":
        form = EditUserProfileForm(request.POST, request.FILES, instance=ins)
        if form.is_valid():
            instance = form.save(commit=False)
            # userprofile.user = request.user
            instance.save()
            return redirect(reverse("Home:view_profile"))
        else:
            context = {
                "description": ins.description,
                "city": ins.city,
                "website": ins.website,
                "instance": ins,
                "form": form,
            }
            return render(request, "nagpy/userprofile_edit.html", context)
    else:
        form = EditUserProfileForm(instance=ins)
        context = {
            "description": ins.description,
            "city": ins.city,
            "website": ins.website,
            "instance": ins,
            "form": form,
        }
        return render(request, "nagpy/userprofile_edit.html", context)


def dashboard(request):
    event_list = Event.objects.filter(manager_id=request.user).all()
    args = {"events": event_list}
    return render(request, "nagpy/dashboard.html", args)


def edit_event(request, pk):
    usr = get_object_or_404(Event, pk=pk)

    if usr.manager == request.user:
        if request.POST:
            form = EditEventForm(request.POST, instance=usr)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                return redirect(reverse("Home:dashboard"))
            else:
                args = {"usr": usr, "pk": pk, "form": form}
                return render(request, "nagpy/edit_event.html", args)
        else:
            form = EditEventForm(instance=usr)
            args = {"usr": usr, "pk": pk, "form": form}
            return render(request, "nagpy/edit_event.html", args)
    else:
        return redirect(reverse("Home:dashboard"))


NagPy/NagPy/views.py
from django.shortcuts import redirect


def home_redirect(request):
    return redirect("/home/")


NagPy/Home/templates/nagpy/change_password.html
{% extends "base.html" %} {% block head %}
<title>Change Password</title>{% endblock %} 

{% block bodytitle %}
<div class="body-title" id='ttl'>Change Password</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<form action="" method="post" class="form-signin">
    {% csrf_token %} 
    {% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-lg btn-primary btn-block cs-btn">Change Password</button>
</form>
{% endblock %}

NagPy/Home/templates/nagpy/dashboard.html
{% extends "base.html" %}
{% block head %}
<title>Dashboard</title>
{% endblock %}
{% block bodytitle %}
<div class="body-title" id='ttl'>Dashboard</div>
{% endblock %}
{% block body %}
<div class="event-container">

  {% for event in events %}
  <div class="card text-center" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ event.name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted clr">City: {{ event.city }}</h6>
      <p class="card-text">{{ event.description }}</p>
      <p class="card-text">Venue: {{ event.venue }}</p>
      <a href="#" class="card-link disabled">{{ event.date }}</a>
      <a href="#" class="card-link disabled">{{ event.time }}</a>
      <h6 class="card-subtitle mb-2 text-muted clr" style="margin:10px">{{ event.contact }}</h6>
      <a href="{% url 'Home:edit_event' pk=event.pk %}" class="card-link">Edit Event</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

NagPy/Home/templates/nagpy/edit_event.html
{% extends "base.html" %}
{% block head %}
  <title>edit event</title>
{% endblock %}
{% block bodytitle %}
<div class="body-title" id='ttl'>Edit Event</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<form method="post" class="form-signin">
    {% csrf_token %} 
   {% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-lg btn-primary btn-block cs-btn">Submit</button>
</form>

{% endblock %}

NagPy/Home/templates/nagpy/edit_profile.html
{% extends "base.html" %} {% block head %}
<title>Edit Profile</title>{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Edit profile</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<form method="post" class="form-signin">
    {% csrf_token %} 
   {% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-lg btn-primary btn-block cs-btn">Submit</button>
</form>
{% endblock %}

NagPy/Home/templates/nagpy/event_add.html
{% extends 'base.html' %}
{% block head %}
<title>Add Event</title>
{% endblock %}

{% block bodytitle %}
<div class="body-title" id='ttl'>Add Event</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<form method="post" class="form-signin">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Add Event</h1>
    {% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-lg btn-primary btn-block cs-btn">Save</button>
</form>
{% endblock %}

NagPy/Home/templates/nagpy/events_view.html
{% extends 'base.html' %} {% block head %}
<title>Event List</title>
{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Meetups</div>
{% endblock %}
{% block body %}
<div class="event-container">

  {% for event in events %}
  <div class="card text-center" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ event.name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted clr">City: {{ event.city }}</h6>
      <p class="card-text">{{ event.description }}</p>
      <p class="card-text">Venue: {{ event.venue }}</p>
      <a href="#" class="card-link disabled">{{ event.date }}</a>
      <a href="#" class="card-link disabled">{{ event.time }}</a>
      <h6 class="card-subtitle mb-2 text-muted clr" style="margin:10px">{{ event.contact }}</h6>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

NagPy/Home/templates/nagpy/home.html
{% extends 'base.html' %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Home</div>
{% endblock %}
{% block body %}
{% load static %}
<div class="Home-view">
    <img src="{% static 'images/logo.svg' %}" alt="" height="200px" width="300px">
    <h1>Welcome To Nagpy</h1>
    <p><strong>NagPy</strong> is the online portal for Beginners, Intermidiators and expert level programmers to organise meetups and learn by colabrating with different projects.</p>
    <button class="btn btn-lg btn-primary btn-block cs-btn home-btn" src="{% url 'Home:register' %}">Register</button>
</div>
{% endblock %}

NagPy/Home/templates/nagpy/login.html
{% extends 'base.html' %} {% block head %}
<title>Login</title>
{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Login</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<!-- <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" name="login">Login</button>
</form> -->

<div class="fs-container text-center">
    <form class="form-signin" method="post">
        {% load static %}
        <img class="mb-4" src="{% static 'images/python_logo.svg' %}" alt="" width="72" height="72">

        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        {% csrf_token %}


        {% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <div class="checkbox mb-3">
        <label>
                <a href="{% url 'Home:reset_password' %}">forget password</a>
        </label>
      </div>

        <button class="btn btn-lg btn-primary btn-block cs-btn" type="submit" name="login">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2018-2019</p>


    </form>

</div>



{% endblock %}

NagPy/Home/templates/nagpy/logout.html
{% extends 'base.html' %} {% block head %}
<title>Logout</title>
{% endblock %} {% block body %}
<h1>you have been logged out</h1>
{% endblock %}

NagPy/Home/templates/nagpy/profile_view.html
{% extends 'base.html' %} {% block head %}
<title>Profile</title>
{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Profile</div>
{% endblock %}
{% block body %}
<div class="text-center">
<div class="text-center mt-4">
  <div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header p-5 bg-dark"></div>
      <div class="card-body text-center">
        <h5 class="card-title mt-4 mb-0">{{ user.username }}</h5>
        <span>{{ user.email }}</span>
        <p class="card-text mt-2">{{ user.userprofile.description }}</p>
        <p class="card-text mt-2">{{ user.userprofile.city }}</p>
<a href="{% url 'Home:edit_profile' %}" class="card-link">Edit profile</a>
      <a href="{% url 'Home:userprofile_edit' %}" class="card-link">Edit userprofile</a>
      </div>
      <div class="position-absolute profile-pic-wrapper">
        {% load static %}
        {% if user.userprofile.dp %}
          <img src={{ user.userprofile.dp.url }} class="rounded-circle img-thumbnail prof-img-thumb" alt="profile">
        {% else %}
          <img src={% static 'images/default.jpg' %} class="rounded-circle img-thumbnail prof-img-thumb" alt="Mads Obel">
        {% endif %}
      </div>
    </div>
  </div>
</div>  
</div>
</div>
{% endblock %}

NagPy/Home/templates/nagpy/register.html
{% extends 'base.html' %} {% block head %}
<title>Register</title>
{% endblock %}
{% block bodytitle %}
<div class="body-title" id='ttl'>Register</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}
<div class="fs-container">
    <form method='post' class="form-signin">
        {% csrf_token %} 
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }} 
        {% endfor %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }} 
                {% endfor %}
            </div>
        {% endif %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %} 
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %} 
                        {% render_field field class="form-control is-valid" placeholder=field.label %} 
                    {% endif %} 
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %} 
                {% endif %} 
                {% if field.help_text|safe %}
                    <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-primary btn-block cs-btn">Register</button>
    </form>
</div>
{% endblock %}

NagPy/Home/templates/nagpy/reset_password.html
{% extends 'base.html' %} {% block head %}
<title>Reset password</title>
{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Password Reset</div>
{% endblock %}
{% block body %}
{% load widget_tweaks %}

<form method="POST" class="form-signin">

<h1 class="h3 mb-3 font-weight-normal">Password Reset</h1>
<small class="form-text text-muted">
    Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
</small>
    {% csrf_token %} 
{% for hidden_field in form.hidden_fields %} 
            {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %} 
        {% for field in form.visible_fields %}
            <div class="form-group">
                <!-- {{ field.label_tag }}  -->
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %} 
                    {% else %}
                        {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {% endif %}
                {% else %} 
                    {% render_field field class="form-control" placeholder=field.label %}
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    <button type="submit" name="login" class="btn btn-lg btn-primary btn-block cs-btn">reset password</button>
</form>
{% endblock %}

NagPy/Home/templates/nagpy/reset_password_complete.html
{% extends 'base.html' %} {% block head %}
<title>Reset password</title>
{% endblock %} 
{% block bodytitle %}
<div class="body-title" id='ttl'>Password Reset</div>
{% endblock %}
{% block body %}
<div class="text-center">
<h1 class="h3 mb-3 font-weight-normal">Password Reset complete</h1>
<p class="form-text text-muted">
password reset complete you can now login using following link.
<a href="{% url 'Home:login' %}">this link</a>
</p>
</div>
{% endblock %}

NagPy/Home/templates/nagpy/reset_password_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %} {% trans "Please go to the following page and choose a new password:" %} 
{% block reset_link %} {{ protocol }}://{{ domain }}{% url 'Home:password_reset_confirm' uidb64=uid token=token %} 
{% endblock %} 
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }} {% trans "Thanks for using oursite!" %} {% blocktrans %}The {{ site_name }} team{% endblocktrans %} {% endautoescape %}